# box plotting
```{r, collapse=TRUE}
data("iris")
str(iris)
boxplot(as.list(iris[1:50, 1:4]))
boxplot(Sepal.Length ~ Species, data = iris)
pairs(iris[1:4], main = "Anderson's Iris Data -- 3 species",   pch = 21, 
      bg = c("red", "green3", "blue")[unclass(iris$Species)])
```

# decision tree
```{r}
idx <- sample(2, nrow(iris), replace=TRUE, prob=c(0.7, 0.3))
trainData <- iris[idx==1,]
testData <- iris[idx==2,]

#install.packages("party")
require(party)
formula <- Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width
iris_ctree <- ctree(formula, data=trainData)
pred <- predict(iris_ctree, testData)
conf.mat <- table(pred, testData$Species)
(accuracy <- sum(diag(conf.mat))/sum(conf.mat) * 100)
plot(iris_ctree)
```

# data type
```{r}

sex <- factor("m", c("m", "f"))
sex <- factor(c("m", "f", "m"))
sex
nlevels(sex)
levels(sex)
levels(sex) <- c("male", "female") # level 값 전체를 바꾸면, 해당 값을 가진 변수도 변한다. 
sex
ordered(c("a", "b", "c"))
factor(c("a", "b", "c"), ordered=TRUE)
```

# vector
```{r}
x <- c(1, 3, 4)
names(x) <- c("kim", "seo", "park")
x

x[c("kim")]
x["kim"]
nrow(x)
NROW(x)

"a" %in% c("a", "b", "c")
"d" %in% c("a", "b", "c")
setdiff(c("a", "b", "c"), c("a", "d"))
union(c("a", "b", "c"), c("a", "d"))
intersect(c("a", "b", "c"), c("a", "d"))

seq(1, 5)
seq(1, 5, 2)
1:5   # vector를 생성함에 주의

```

#list
```{r}
x <- list(namw="foo", height=70)
x
x <- list(name="foo", height=c(1,3,5))
x$name
x$height
x[1]
x[[1]]
x[2]
x[[2]]

```

#matrix
```{r}
matrix(c(1,2,3,4,5,6,7,8,9),  nrow=3) # column major
matrix(c(1,2,3,4,5,6,7,8,9),  ncol=3)
matrix(c(1,2,3,4,5,6,7,8,9),  nrow=3, byrow=T) # row major
matrix(c(1,2,3,4,5,6,7,8,9),  nrow=3, 
                 dimnames=list(c("item1", "item2", "item3"), 
                               c("feature1", "feature2", "feature3")))

x <- matrix(c(1,2,3,4,5,6,7,8,9),  nrow=3)
rownames(x) <- c("r1", "r2", "r3")
colnames(x) <- c("c1", "c2", "c3")
x

x <- matrix(c(1,2,3,4,5,6,7,8,9),  nrow=3, 
       dimnames=list(c("item1", "item2", "item3"), 
                     c("feature1", "feature2", "feature3")))

x
x[ , "feature2"] >= 5
x[ x[, "feature2"] >= 5 ,]

x
x[ , 2]>=5
x[x[ , 2]>=5, ]

```

# matrix transpose
```{r}
x <- matrix(c(1,2,3,4,5,6,7,8,9),  nrow=3)
x
t(x)
ncol(x)
nrow(x)
x %*% t(x)
x * t(x)

```

# data.frame
```{r}
d <- data.frame(x=c(1,2,3,4,5), y=c(2,4,6,8,10))
d
x <- c(1,2,3,4,5)
y <- c(2,4,6,8,10)
z <- c("M", "F", "M", "F", "M")
d <- data.frame(x, y, z)
d
str(d)
d <- data.frame(x, y, z, stringsAsFactors = F)
str(d) # 확인
d$v <- c(3, 6, 9, 12, 15)
d
d$v2 <- c(10, 20, 30, 40, 50)
d
d$x
d[1, ]
d[ , "v"]
d[ , c("x", "v")]
d[d$x>3, ]
d[ , "v", drop=F]

x <- data.frame(1:3, 11:13)
x
colnames(x) <- c("col1", "col2")
x
rownames(x) <- c("row1", "row2", "row3")
x

x <- data.frame(matrix(c(1,2,3,4), ncol=2))
x
colnames(x) <- c("X", "Y")
x <- data.frame(list(x=c(1,2), y=c(3,4)))
str(x)

```

# if statements
```{r}

x <- c(1,2,3,4,5)
result <- ifelse( x %% 2 == 0, "even", "odd")
result
```

# for statements
```{r}
for (i in 1:10) { print(i) }

i <- 1
repeat {
  print(i)
  if (i >= 10) { break }
  i <- i+1
}

i <- 0
while (i < 10){
  print(i)
  i <- i+1
}

```

# vector operation
```{r}
d <- data.frame(x=c(1,2,3,4,5), y=c("a", "b", "c", "d", "e"))
d
d[c(TRUE, FALSE, TRUE, FALSE, TRUE), ]
d[d$x%%2==0, ]
sum(c(1,2,3,4,5))
sum(c(1,2,3,4,NA))
sum(c(1,2,3,4,NA), na.rm = TRUE)
mean(c(1,2,3,4,NA))
mean(c(1,2,3,4,NA), na.rm = TRUE)

x <- data.frame(a=c(1,2,3), b=c("a", NA, "c"), c=c("a", "b", NA))
x
na.omit(x)

```

# functions
```{r}
fibo <- function(n){
  if (n==1 || n==2) { return(1)}
  else { return(fibo(n-1)+fibo(n-2))}
}

fibo(2)
fibo(10)

f <- function(x, y) { print(x); print(y)}
f(1,2)
x <- c(1,2,3)
y <- c(10, 20, 30)
f(x, y)

g <- function(z, ...){
  print(z)
  f(...)
}

g(1,2,3)

```

# call-by-value
```{r}
f <- function(x,i) {x[i] <- 4}
w<-c(10,11,12,13)
print(f(w, 1))
w

```


# read/write CSV
```{r}
setwd("~/R/workspace/lecture/data")
x <- read.csv("a.csv", stringsAsFactors = F)
x <- read.csv("a.csv", na.strings = c("NIL"))
write.csv(x, "b.csv", row.names = F)

```

# read Excel data I/O
```{r}
#install.packages("xlsx")
require(xlsx)
#install.packages("rJava")
#Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre1.8.0_91")

titanic <- read.xlsx("titanic3.xls", sheetIndex=1)
str(titanic)
head(titanic)
tnames <- colnames(titanic)
View(titanic)
tnames
titanic$name <- as.character(titanic$name)
str(titanic)


file <- "./usarrests.xlsx"
res <- write.xlsx(USArrests, file)  

```

# 객체 삭제
```{r}
ls()
rm(list = ls())
rm(list = c("x", "y"))

```

# apply() 계열 함수
```{r}
head(iris)
apply(iris[, 1:4], 2, sum)
apply(iris[, 1:4], 2, mean)
apply(iris[, 1:4], 2, median)

colSums(iris[, 1:4])

apply(iris[ , 1], 2, sum) # doesn't work 
colSums(iris[ , 1])       # doesn't work
sum(iris[, 1])

f2 <- function(x) { return(x*2)}
result <- lapply(1:3, f2)
result
unlist(result) # list to vecor


(result <- lapply(iris[, 1:4], mean))
unlist(result)
colMeans(iris[, 1:4])

res <- unlist(lapply(iris[, 1:4], mean))
m <- matrix(res, ncol=4, byrow=TRUE)
d <- as.data.frame(m)
d
names(d) <- names(iris[, 1:4])
d

data.frame(do.call(cbind, lapply(iris[, 1:4], mean)))

x <- sapply(iris[, 1:4], mean)
x
as.data.frame(x)
as.data.frame(t(x))

x <- as.matrix(iris[, 1:4])
x
x %*% t(x)
t(x) %*% x

# 결과가 matrix인 sapply()의 예
y <- sapply(iris[, 1:4], function(x) { x>3 })
y

mapply(paste,
       c(1,2,3,4,5),
       c("a", "b", "c", "d", "e"),
       c("A", "B", "C", "D", "E"),
       MoreArgs=list(sep="-"))

# tapply()
rep(1, 10)
tapply(1:10, rep(1, 10), sum)
tapply(1:10, 1:10 %% 2 == 1, sum)
tapply(iris$Sepal.Length, iris$Species, mean)


# sorting
x <- c(20, 11, 33, 50, 47)
sort(x)
sort(x, decreasing = T)

order(x)
order(-x)

worder <- order(iris$Sepal.Width)
iris[worder, ]
head(iris[worder, ])

table(iris$Species)

llist <- split(iris$Sepal.Length, iris$Species)
sapply(llist, mean)
# 동일한 코드
tapply(iris$Sepal.Length, iris$Species, mean)
```


# subset
```{r}
iris
subset(iris, iris$Species == "setosa")
iris[iris$Species=="setosa", ]

subset(iris, iris$Species == "setosa" & Sepal.Length > 5.0)
iris[iris$Species=="setosa" & iris$Sepal.Length > 5.0, ]

subset(iris, iris$Species == "setosa" & Sepal.Length > 5.0, select=c(Sepal.Length, Species))
```

