# iris
## kmeans
```{r}
data(iris)
library(stats)
myiris <-iris
myiris$Species <-NULL  # Species 컬럼 제거
myiris.kmeans <- kmeans(myiris, centers=3)
myiris.kmeans <- kmeans(myiris, 3)  # 위와 동일한 표현

table(iris$Species, myiris.kmeans$cluster)
conf.mat <- table(iris$Species, myiris.kmeans$cluster)
(accuracy <- sum(diag(conf.mat))/sum(conf.mat) * 100)

new.mat <- data.frame("c1"=conf.mat[,2], "c3"=conf.mat[,1], "c2"=conf.mat[,3])
new.mat <- as.matrix(new.mat) # 간단히 => new.mat <-  conf.mat[, c(2,1,3)]
(accuracy <- sum(diag(new.mat))/sum(new.mat) * 100)

myiris.kmeans
plot(myiris[c("Sepal.Length", "Sepal.Width")], col=myiris.kmeans$cluster)
points(myiris.kmeans$centers[,c("Sepal.Length","Sepal.Width")], col=1:3, pch="*", cex=5)

myiris.kmeans$centers
ave <- 0
for(i in 1:ncol(myiris)) ave[i]<- sum(myiris.kmeans$centers[,i])/nrow(myiris.kmeans$centers)
ave  # 출력 

# scaling 한 후 clustering 수행
myiris_z <- as.data.frame(lapply(myiris, scale))  # z-score 계산
myiris_z.kmeans <- kmeans(myiris_z, centers=3)
#table(iris$Species, myiris_z.kmeans$cluster)
conf.mat <- table(iris$Species, myiris.kmeans$cluster)
new.mat <-  conf.mat[, c(2,3,1)]; new.mat
(accuracy <- sum(diag(new.mat))/sum(new.mat) * 100)

myiris_z.kmeans$centers
```

## K-medois
```{r}
library(cluster)
myiris.pam <- pam(myiris,3)
conf.mat <- table (myiris.pam$clustering, iris$Species)
new.mat <-  conf.mat[, c(1,2,3)]; new.mat
(accuracy <- sum(diag(new.mat))/sum(new.mat) * 100)
```

## hclust
```{r}
sim_eu <- dist(myiris, method="euclidean")
dendrogram <-hclust(sim_eu^2, method="single")
plot(dendrogram, hang = -1)
plot(dendrogram, hang = -1, labels=iris$Species)
cluster <- cutree(dendrogram, k=3)
table(iris$Species, cluster)

sim_eu <- dist(myiris,  method="minkowski")
dendrogram <-hclust(sim_eu^2,  method="complete")

cluster <- cutree(dendrogram, k=3)
conf.mat <- table(iris$Species, cluster)
conf.mat
(accuracy <- sum(diag(conf.mat))/sum(conf.mat) * 100)

sim_eu <- dist(myiris,  method="minkowski")
dendrogram <-hclust(sim_eu^2,  method="ward.D")

```


## DBScan, 밀도기반 클러스터링
```{r}
library(fpc)
myiris <- iris[-5]
myiris.ds <- dbscan(myiris, eps=0.42, MinPts=5)
table(myiris.ds$cluster, iris$Species)

plot(myiris.ds, myiris)
plot(myiris.ds, myiris[c(1,4)])
plotcluster(myiris, myiris.ds$cluster) # projection

```


# Clustering for Wine data
```{r}
library(HDclassif)
data(wine)
head(wine)

mywine <- wine[,-1]  # 1번째 컬럼 삭제 , mywine$class <- NULL
mywine <-scale(mywine)
km <- kmeans(mywine, centers=3)
ss <-km$withinss
conf.mat <- table(wine$class, km$cluster)
(accuracy <- sum(diag(conf.mat))/sum(conf.mat) * 100)
plot(mywine[c("V1","V2")], col=km$cluster)
points(km$centers[ , c("V1","V2")], col=1:3, pch=8, cex=2)
ss <-0
for(i in 1:15) ss[i] <- sum(kmeans(mywine, centers=i)$withinss)
plot(1:15, ss, type="b", xlab="클러스터 개수", ylab="각 클러스터 SS의 합")

# HAC
sim_eu <- dist(mywine, method="euclidean")
dendrogram <-hclust(sim_eu^2, method="ward.D2")
cluster <- cutree(dendrogram, k=3)
conf.mat <- table(wine$class, cluster)
(accuracy <- sum(diag(conf.mat))/sum(conf.mat) * 100)

# feature selection
mywine <- wine
subfeatures <- cfs(class~., wine)
subfeatures  # 선택된 feature를 확인
mywine <- wine[subfeatures]
km <-kmeans(mywine,3)
conf.mat <- table(wine$class, km$cluster)
(accuracy <- sum(diag(conf.mat))/sum(conf.mat) * 100)
```

# Association Rule Mining
```{r}
dvd <- read.csv("dvdtrans.csv", header = TRUE, as.is = TRUE); dvd
dvd.list <- split(dvd$Item, dvd$ID); dvd.list
# transaction ID별로 하나의 레코드가 되도록 변환
library(arules); library(arulesViz)
dvd.trans <- as(dvd.list, "transactions")
dvd.trans
summary(dvd.trans)
image(dvd.trans)
dvd.rules <- apriori(dvd.trans)
inspect(dvd.rules)
dvd.rules <- apriori(dvd.trans, parameter = list(support = 0.2, confidence = 0.6)); inspect(dvd.rules)
dvd.rules.sorted <- sort(dvd.rules, by="confidence"); inspect(dvd.rules.sorted)

plot(dvd.rules)
plot(dvd.rules, measure=c("confidence", "lift"))
plot(dvd.rules, method = "matrix", measure=c("confidence", "lift"), control=list(reorder=TRUE))
plot(dvd.rules, method = "grouped")
plot(dvd.rules, method = "graph")
plot(dvd.rules, method = "graph", control = list(type = "items"))
```




